### ISSUE TITLE
What does V8 here?

### ISSUE THREAD

**Issue by phaverty** [Genentech/FacileDataSet#24]
FacileExplorer uses V8. It's a tough dependency. What is is used for?

**Comment by jonocarroll** [comment]
We can find out... just grep "V8::"... oh, right. :stuck_out_tongue_winking_eye:

**Comment by phaverty** [comment]
Cute :-)
Luckily V8 exports only 3 functions and we do not use them.  Looks like it works without V8.

**Comment by lianos** [comment]
I believe it's required due to some mojo I was trying to use with shinyjs.

I also have V8 as an import on my multiGSEA.shiny package, which TFE uses quite a bit.

Pretty sure you can't nuke it. What's so tough about the dependency? Havent had a problem with it ... even when having to deploy on GNE infrastructure ;-)

**Comment by phaverty** [comment]
Looks like V8 is actually needed.  The V8 system library is a bit of a hassle for some of our dedicated machines that we are building. We'll sort it out.
